#!/bin/bash

vnc_viewer="$(snapctl get vnc-viewer)"
vnc_port="$(snapctl get vnc-port)"

ssh -T -L "${vnc_port:-5900}:localhost:5900" "$@" -- "sleep infinity"&
ssh_pid=$!
"${vnc_viewer:-gvncviewer}" localhost
kill "${ssh_pid}"
