name: frame-it
base: core20
version: '1.0'
summary: Utilities for working with Ubuntu Frame on desktop systems
description: |
  *frame-it* makes it easy to use Ubuntu Frame on the desktop:
  
  * `frame-it.check` checks Ubuntu Frame is installed plus options frame-it uses
  * `frame-it gnome-calendar` will run `gnome-calendar` using Ubuntu Frame
  * `snap set frame-it shell-app=gnome-calendar` sets the `shell-app` option
  * `frame-it.shell` will run Ubuntu Frame using the `shell-app` option
  * `sudo frame-it.root-on-x11` will run Ubuntu Frame as root using X11

  When `shell-app` is set a login shell is provided from the greeter: Logging 
  into "frame-it" will run Ubuntu Frame using the `shell-app` option as a user
  session

grade: stable
confinement: classic

apps:
  frame-it:
    command: frame-it

  check:
    command: frame-it-check

  shell:
    command: frame-it-shell

  root-on-x11:
    command: frame-it-root-on-x11

parts:
  frame-it:
    plugin: dump
    source: frame-it

architectures:
  - build-on: amd64
    run-on: all